### PR TITLE
Fix v4.5's talent screen shenanigans

### PR DESCRIPTION
**Pull request by MRDGH2821**
Adjusted the talent box scan coordinates.
Now it should be able to grab talent levels properly in v4.5

Tested in 1600x900 resolution.

### CODE REVIEW

**Comment by MRDGH2821** [comment]
Fixes #512

**Comment by Cupcak3** [comment]
Please undo the changes to add the installer and to the assembly cs file. 

They're not relevant to the pull request and would probably affect my project solution on my computer that I'd rather not possibly deal with 😅

**Comment by MRDGH2821** [comment]
Reverted. That commit exists in separate branch now

**Review by Dyl-Aeon — APPROVED** [review]
Tested and working in 16:9 resolutions

**Comment by Cupcak3** [comment]
I totally forgot to merge this request before making the build ;-; sorry. Please feel free to continue pull requests for other bugs that pop up

**Comment by MRDGH2821** [comment]
No worries, on a side note, I may start cleaning up the project & code. It was triggering my OCD 😅😂

**Pull request closed without merging**
