### PR TITLE
Fixes the Tartaglia passive fix.

### PR DESCRIPTION
**Pull request by Nikolas-VIII**
Requires a full party to work properly (4 Characters).

### CODE REVIEW

**Comment by Cupcak3** [comment]
I'm not sure I like the way this PR code change is written. It is a bit too vague. Can you confirm to me how his passive works and exactly which characters talents it raises?

**Comment by Nikolas-VIII** [comment]
If he is not in the active party, only his own talent level is affected.
If he is in the party. The Talent levels of all characters, that are currently in the party are affected.

My change to the code selects the first character in the party prior to scanning.
Then checks if an Ascension level 4 Tartaglia is on the account.
If so, it changes only Tartaglia’s Talent level if he is not in the party.
And changes the Talent level of the first four characters if he is in the party.

If all conditions are met for the last scenario, but only 3 characters are equipped, the talent level of the first character after the equipped party would be misreported.
Also, if the key for switching to the first character was changed from the “1” key, the starting point of the character scan would be shifted, resulting in a similar problem (if an Ascension 4 Tartaglia is in the party).

To fix this, it could be possible to determine the current party size, by looking at the color of the rings used for the character icons on top of the character-screen. Or perhaps at the color of the normal attack talent level (It is blue if it is affected by Tartaglias passive, like the other Talent levels are, when affected by the corresponding characters Constellation 3 & 5).


In any case, IIRC on Version 1.2.7 the normal attack talent level of all characters, except for Tartaglia’s (or the characters in the active party with him) gets misreported, if there is an Ascension 4 Tartaglia on the account.

**Comment by Cupcak3** [comment]
What is the motivation to selecting the first character in the party before entering the character details screen?

**Comment by Cupcak3** [comment]
Checking for the color of the normal attack talent level and number of on-field party characters are not very practical solutions.

Knowing how his passive works now, my train of thought is to:

1. scan all characters with the assumption that they have 4 party characters
2. check if Tartaglia is or isn't in the on-field party
3. check if his ascension activates his passive
4. adjust auto attack levels accordingly

**Comment by Nikolas-VIII** [comment]
When pressing “C” the character screen opens on the currently equipped character.
When selecting the first character, the first four scanned characters are the current party.
If, for example the second character is scanned first, the first character in the party would get scanned last.

My solution checks if Tartaglia is in the first 4 scanned characters and applies the changes to those 4 scanned characters, if applicable.

**Comment by Nikolas-VIII** [comment]
My solution should be pretty much that, with point 2 and 3 swapped.

**Comment by Cupcak3** [comment]
I see. Good catch. Have you verified this code works as intended? I don't have the character so I can't test it myself

**Comment by Nikolas-VIII** [comment]
Yes. I tested it with Tartaglia in the party and without.

**Review by ChewyFlyer — APPROVED** [review]

**Comment by ChewyFlyer** [comment]
Oh I'm sorry I didn't think it'd actually do something, please ignore the "approved" thingy, and apologies for any inconvenience

**Pull request merged**
